# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/DJANGO-NIKITA/MoreliaTalk/morelia_client_qt/module/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setEnabled(True)
        self.ExitButton.setGeometry(QtCore.QRect(405, 0, 45, 30))
        self.ExitButton.setAutoFillBackground(False)
        self.ExitButton.setText("")
        self.ExitButton.setAutoDefault(False)
        self.ExitButton.setDefault(False)
        self.ExitButton.setFlat(False)
        self.ExitButton.setObjectName("ExitButton")
        self.ResizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResizeButton.setEnabled(True)
        self.ResizeButton.setGeometry(QtCore.QRect(360, 0, 45, 30))
        self.ResizeButton.setAutoFillBackground(False)
        self.ResizeButton.setText("")
        self.ResizeButton.setAutoDefault(False)
        self.ResizeButton.setDefault(False)
        self.ResizeButton.setFlat(False)
        self.ResizeButton.setObjectName("ResizeButton")
        self.MinimazeButton = QtWidgets.QPushButton(self.centralwidget)
        self.MinimazeButton.setEnabled(True)
        self.MinimazeButton.setGeometry(QtCore.QRect(315, 0, 45, 30))
        self.MinimazeButton.setAutoFillBackground(False)
        self.MinimazeButton.setText("")
        self.MinimazeButton.setAutoDefault(False)
        self.MinimazeButton.setDefault(False)
        self.MinimazeButton.setFlat(False)
        self.MinimazeButton.setObjectName("MinimazeButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass
