# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/message_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageCard(object):
    def setupUi(self, MessageCard):
        MessageCard.setObjectName("MessageCard")
        MessageCard.resize(94, 50)
        self.verticalLayout = QtWidgets.QVBoxLayout(MessageCard)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WidgetContent = QtWidgets.QWidget(MessageCard)
        self.WidgetContent.setObjectName("WidgetContent")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.WidgetContent)
        self.vboxlayout.setObjectName("vboxlayout")
        self.usernameLabel = QtWidgets.QLabel(self.WidgetContent)
        self.usernameLabel.setObjectName("usernameLabel")
        self.vboxlayout.addWidget(self.usernameLabel)
        self.textLabel = QtWidgets.QLabel(self.WidgetContent)
        self.textLabel.setObjectName("textLabel")
        self.vboxlayout.addWidget(self.textLabel)
        self.verticalLayout.addWidget(self.WidgetContent)

        self.retranslateUi(MessageCard)
        QtCore.QMetaObject.connectSlotsByName(MessageCard)

    def retranslateUi(self, MessageCard):
        _translate = QtCore.QCoreApplication.translate
        MessageCard.setWindowTitle(_translate("MessageCard", "Form"))
        self.usernameLabel.setText(_translate("MessageCard", "TextLabel"))
        self.textLabel.setText(_translate("MessageCard", "TextLabel"))
