# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './interfaces/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.InputArea = QtWidgets.QHBoxLayout()
        self.InputArea.setContentsMargins(0, 0, 0, 0)
        self.InputArea.setSpacing(5)
        self.InputArea.setObjectName("InputArea")
        self.InputText = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputText.sizePolicy().hasHeightForWidth())
        self.InputText.setSizePolicy(sizePolicy)
        self.InputText.setMinimumSize(QtCore.QSize(10, 10))
        self.InputText.setObjectName("InputText")
        self.InputArea.addWidget(self.InputText)
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton.sizePolicy().hasHeightForWidth())
        self.SendButton.setSizePolicy(sizePolicy)
        self.SendButton.setMinimumSize(QtCore.QSize(0, 0))
        self.SendButton.setObjectName("SendButton")
        self.InputArea.addWidget(self.SendButton)
        self.InputArea.setStretch(0, 5)
        self.InputArea.setStretch(1, 1)
        self.gridLayout.addLayout(self.InputArea, 1, 1, 1, 1)
        self.ChatListArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatListArea.sizePolicy().hasHeightForWidth())
        self.ChatListArea.setSizePolicy(sizePolicy)
        self.ChatListArea.setWidgetResizable(True)
        self.ChatListArea.setObjectName("ChatListArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 313, 528))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ChatListArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ChatListArea, 0, 0, 2, 1)
        self.MessageArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageArea.sizePolicy().hasHeightForWidth())
        self.MessageArea.setSizePolicy(sizePolicy)
        self.MessageArea.setWidgetResizable(True)
        self.MessageArea.setObjectName("MessageArea")
        self.MessageAreaContent = QtWidgets.QWidget()
        self.MessageAreaContent.setGeometry(QtCore.QRect(0, 0, 628, 471))
        self.MessageAreaContent.setObjectName("MessageAreaContent")
        self.MessageAreaContentLayout = QtWidgets.QGridLayout(self.MessageAreaContent)
        self.MessageAreaContentLayout.setContentsMargins(5, 5, 5, 5)
        self.MessageAreaContentLayout.setSpacing(5)
        self.MessageAreaContentLayout.setObjectName("MessageAreaContentLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.MessageAreaContentLayout.addItem(spacerItem, 0, 0, 1, 2)
        self.MessageArea.setWidget(self.MessageAreaContent)
        self.gridLayout.addWidget(self.MessageArea, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setRowStretch(0, 9)
        self.gridLayout.setRowStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SendButton.setText(_translate("MainWindow", "PushButton"))
