# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\DJANGO-NIKITA\MoreliaTalk\morelia_client_qt\src\interfaces\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.CustomTitleBar = QtWidgets.QHBoxLayout()
        self.CustomTitleBar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.CustomTitleBar.setSpacing(0)
        self.CustomTitleBar.setObjectName("CustomTitleBar")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.CustomTitleBar.addItem(spacerItem)
        self.MinimazeButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinimazeButton.sizePolicy().hasHeightForWidth())
        self.MinimazeButton.setSizePolicy(sizePolicy)
        self.MinimazeButton.setMinimumSize(QtCore.QSize(45, 30))
        self.MinimazeButton.setText("")
        self.MinimazeButton.setObjectName("MinimazeButton")
        self.CustomTitleBar.addWidget(self.MinimazeButton)
        self.ResizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResizeButton.setMinimumSize(QtCore.QSize(45, 30))
        self.ResizeButton.setText("")
        self.ResizeButton.setObjectName("ResizeButton")
        self.CustomTitleBar.addWidget(self.ResizeButton)
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setEnabled(True)
        self.ExitButton.setMinimumSize(QtCore.QSize(45, 30))
        self.ExitButton.setText("")
        self.ExitButton.setObjectName("ExitButton")
        self.CustomTitleBar.addWidget(self.ExitButton)
        self.gridLayout.addLayout(self.CustomTitleBar, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
